<a href="https://colab.research.google.com/github/EddyKubwimana/machine_learning/blob/main/matrix%20manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 pip install sympy

In [ ]:
from sympy import*

In [ ]:
dp = Matrix([[12,10,-6,8,4,-14,0], [-7,-6,4,-5,-7,9,0], [9,9,-9,9,9,-18,0],[-4,-3,-1,0,-8,1,0],[8,7,-5,6,1,-11,0]])

In [ ]:
m = Matrix([[2,-1,0],[-3,1,-1],[2,-3,4]])

In [ ]:
dp

Matrix([
[12, 10, -6,  8,  4, -14, 0],
[-7, -6,  4, -5, -7,   9, 0],
[ 9,  9, -9,  9,  9, -18, 0],
[-4, -3, -1,  0, -8,   1, 0],
[ 8,  7, -5,  6,  1, -11, 0]])

In [ ]:
 dp.col_del(3)
 dp.col_del(4)

In [ ]:
a1

In [ ]:
dp

Matrix([
[12, 10, -6,  4, 0],
[-7, -6,  4, -7, 0],
[ 9,  9, -9,  9, 0],
[-4, -3, -1, -8, 0],
[ 8,  7, -5,  1, 0]])

In [ ]:
dp.rref()

(Matrix([
 [1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0]]),
 (0, 1, 2, 3))

In [ ]:
PA, PE, PM, PT = sp.symbols("PA,PE,PM,PT")

In [ ]:
variable = sp.Matrix([PA,PE,PM,PT])

In [ ]:
equation = dp*variable

In [ ]:
answer = sp.solve(equation,variable)

In [ ]:
answer



{PA: 0.0, PE: 0.0, PM: 0.0, PT: 0.0}

In [ ]:
import numpy as np


In [ ]:
data = [[0.35, -0.3, -0.3, -0.2], [-0.1, 0.9,-0.15, -0.1], [-0.25, -0.35,0.85,-0.1],[0,-0.25,-0.4, 0.6]]

In [ ]:
def rref(matrix):
    A = np.array(matrix, dtype=np.float64)

    i = 0 # row
    j = 0 # column
    while True:
        # find next nonzero column
        while all(A.T[j] == 0.0):
            j += 1
            # if reached the end, break
            if j == len(A[0]) - 1 : break
        # if a_ij == 0 find first row i_>=i with a
        # nonzero entry in column j and swap rows i and i_
        if A[i][j] == 0:
            i_ = i
            while A[i_][j] == 0:
                i_ += 1
                # if reached the end, break
                if i_ == len(A) - 1 : break
            A[[i, i_]] = A[[i_, i]]
        # divide ith row a_ij to make it a_ij == 1
        A[i] = A[i] / A[i][j]
        # eliminate all other entries in the jth column by subtracting
        # multiples of of the ith row from the others
        for i_ in range(len(A)):
            if i_ != i:
                A[i_] = A[i_] - A[i] * A[i_][j] / A[i][j]
        # if reached the end, break
        if (i == len(A) - 1) or (j == len(A[0]) - 1): break
        # otherwise, we continue
        i += 1
        j += 1

    return A

In [ ]:
solution = rref(data)

In [ ]:
solution

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
import numpy as np

In [ ]:
zeros = np.zeros((3,3),dtype=np.int)

<ipython-input-2-7b9b0e554b61>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  zeros = np.zeros((3,3),dtype=np.int)


In [ ]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
ones = np.ones((5,5),dtype = np.int)

<ipython-input-4-923f9497060a>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ones = np.ones((5,5),dtype = np.int)


In [ ]:
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
vector = np.array([1,2,3])
vector
sum = vector*2
sum

array([2, 4, 6])

In [ ]:
identityArray = np.identity(4, dtype = np.int)
identityArray

<ipython-input-11-db8c2bb20307>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  identityArray = np.identity(4, dtype = np.int)


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
identityArray[:,0:3]

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [ ]:
array = np.array([[1,3,4],[1,3,4],[1,3,4]])
array

array([[1, 3, 4],
       [1, 3, 4],
       [1, 3, 4]])

In [ ]:
array.sum(axis=0)

array([ 3,  9, 12])

In [ ]:
np.sum(array, axis =0)

array([ 3,  9, 12])

In [ ]:
np.product(array, axis =0)

array([ 1, 27, 64])

In [ ]:
newArray = array.reshape(9,1)

In [ ]:
newArray

array([[1],
       [3],
       [4],
       [1],
       [3],
       [4],
       [1],
       [3],
       [4]])

In [ ]:
np.min(array, axis = 1)

array([1, 1, 1])

In [ ]:
import pandas as pd
data = {1:1, 2:2,3:3,4:4, 5:5,6:6,7:7,8:8,9:9,10:10,11:11}


In [ ]:
data = pd.Series(data, index = [1,2,3,4,5,6,7,8,9,10,11],name = "Trials")

In [ ]:
data

1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
Name: Trials, dtype: int64

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df.head()

Trials
1       1
2       2
3       3
4       4
5       5

In [ ]:
df.Trials

1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
Name: Trials, dtype: int64

In [ ]:
data.iloc[0:2]

1    1
2    2
Name: Trials, dtype: int64

In [ ]:
data.loc[1:2]

1    1
2    2
Name: Trials, dtype: int64

In [ ]:
letters = pd.Series(["a","a","b","c"], index = ["a","a","b","c"])

In [ ]:
letters.loc["a"]

a    a
a    a
dtype: object

In [ ]:
numbers = pd.Series([1,1,1,2,2,3,3], index =[1,1,1,2,2,3,3])

In [ ]:
numbers.iloc[0:2]

1    1
1    1
dtype: int64

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])